// Define the lessons array
const lessons = [
    {
      id: 1,
      subject: "Maths",
      location: "Russia",
      price: 55,
      spaces: 5,
      image: "images/s1.png", // Update the path to your image
      availableInventory: 10,
    },
    {
      id: 2,
      subject: "Drama",
      location: "Spain",
      price: 80,
      spaces: 10,
      image: "images/s2.png",
      availableInventory: 10,
    },
    {
      id: 3,
      subject: "Accounting",
      location: "Germany",
      price: 50,
      spaces: 5,
      image: "images/s12.png",
      availableInventory: 10,
    },
    {
      id: 4,
      subject: "Journaling",
      location: "Mexico",
      price: 10,
      spaces: 8,
      image: "images/s11.png",
      availableInventory: 10,
    },
    {
      id: 5,
      subject: "Coding",
      location: "London",
      price: 50,
      spaces: 7,
      image: "images/s10.png",
      availableInventory: 10,
    },
    {
      id: 6,
      subject: "Baking",
      location: "Turkey",
      price: 45,
      spaces: 8,
      image: "images/s9.png",
      availableInventory: 10,
    },
    {
      id: 7,
      subject: "Music",
      location: "Azerbaijan",
      price: 70,
      spaces: 5,
      image: "images/s8.png",
      availableInventory: 10,
    },
    {
      id: 8,
      subject: "Psychology",
      location: "Georgia",
      price: 90,
      spaces: 12,
      image: "images/s7.png",
      availableInventory: 10,
    },
    {
      id: 9,
      subject: "Business",
      location: "Argentina",
      price: 20,
      spaces: 8,
      image: "images/s6.png",
      availableInventory: 10,
    },
    {
      id: 10,
      subject: "Art",
      location: "Italy",
      price: 50,
      spaces: 6,
      image: "images/s5.png",
      availableInventory: 10,
    }
  ];
  